-- =============================================================================
-- Module 5 — Marketing Campaign Management (SRS §6.7)
-- =============================================================================

CREATE TABLE campaigns (
  id BIGSERIAL PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenants(id),
  name VARCHAR(150) NOT NULL,
  description TEXT,
  channel VARCHAR(20) NOT NULL
    CHECK (channel IN ('email', 'social_media', 'sms', 'event', 'webinar', 'paid_ads', 'other')),
  status VARCHAR(20) NOT NULL DEFAULT 'draft'
    CHECK (status IN ('draft', 'active', 'paused', 'completed', 'cancelled')),
  start_date DATE,
  end_date DATE,
  budget NUMERIC(12, 2) NOT NULL DEFAULT 0,
  actual_cost NUMERIC(12, 2) NOT NULL DEFAULT 0,
  -- Marketing staffer running this campaign — drives the "own"/"all" data scope
  -- for the marketing_executive role (see permission.constant.js ROLE_DATA_SCOPE).
  owner_id BIGINT REFERENCES users(id),
  created_by BIGINT REFERENCES users(id),
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE INDEX idx_campaigns_tenant ON campaigns(tenant_id);
CREATE INDEX idx_campaigns_owner ON campaigns(owner_id);

-- FR-5.3/BR: leads generated by a campaign — nullable since most lead sources
-- (referral, cold call, exhibition, ...) aren't campaign-driven.
ALTER TABLE leads ADD COLUMN campaign_id BIGINT REFERENCES campaigns(id);
CREATE INDEX idx_leads_campaign ON leads(campaign_id);
